exports.defaultExamFinalGrades = [
  {
    subjgradeseq: 1,
    subjmin: "0.00",
    subjmax: "44.99",
    subjgrade: "F",
    subjgpa: "0.0",
    subjresult: "GAGAL",
    active: true,
  },
  {
    subjgradeseq: 2,
    subjmin: "45.00",
    subjmax: "49.99",
    subjgrade: "D",
    subjgpa: "1.0",
    subjresult: "LULUS",
    active: true,
  },
  {
    subjgradeseq: 3,
    subjmin: "50.00",
    subjmax: "54.99",
    subjgrade: "C",
    subjgpa: "2.0",
    subjresult: "MEMUASKAN",
    active: true,
  },
  {
    subjgradeseq: 4,
    subjmin: "55.00",
    subjmax: "59.99",
    subjgrade: "C+",
    subjgpa: "2.3",
    subjresult: "BAIK",
    active: true,
  },
  {
    subjgradeseq: 5,
    subjmin: "60.00",
    subjmax: "64.99",
    subjgrade: "B-",
    subjgpa: "2.6",
    subjresult: "BAIK",
    active: true,
  },
  {
    subjgradeseq: 6,
    subjmin: "65.00",
    subjmax: "69.99",
    subjgrade: "B",
    subjgpa: "3.0",
    subjresult: "BAIK",
    active: true,
  },
  {
    subjgradeseq: 7,
    subjmin: "70.00",
    subjmax: "74.99",
    subjgrade: "B+",
    subjgpa: "3.3",
    subjresult: "SANGAT BAIK",
    active: true,
  },
  {
    subjgradeseq: 8,
    subjmin: "75.00",
    subjmax: "84.99",
    subjgrade: "A-",
    subjgpa: "3.6",
    subjresult: "CEMERLANG",
    active: true,
  },
  {
    subjgradeseq: 9,
    subjmin: "85.00",
    subjmax: "100.00",
    subjgrade: "A",
    subjgpa: "4.0",
    subjresult: "CEMERLANG",
    active: true,
  },
];
